headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'none',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
}

category = {

    "all category": "all",
    "3D": "/catalog/3d",
    "60 favorites": "/catalog/60_favorites",
    "abstract": "/catalog/abstract",
    "anime": "/catalog/anime",
    "art": "/catalog/art",
    "vector": "/catalog/vector",
    "city": "/catalog/city",
    "food": "/catalog/food",
    "animals": "/catalog/animals",
    "space": "/catalog/space",
    "love": "/catalog/love",
    "macro": "/catalog/macro",
    "cars": "/catalog/cars",
    "minimalism": "/catalog/minimalism",
    "motorcycles": "/catalog/motorcycles",
    "music": "/catalog/music",
    "holidays": "/catalog/holidays",
    "nature": "/catalog/nature",
    "other": "/catalog/other",
    "words": "/catalog/words",
    "smilies": "/catalog/smilies",
    "sport": "/catalog/sport",
    "textures": "/catalog/textures",
    "dark": "/catalog/dark",
    "hi-tech": "/catalog/hi-tech",
    "fantasy": "/catalog/fantasy",
    "flowers": "/catalog/flowers",
    "black": "/catalog/black",

}